#!/usr/bin/env python3
"""Turn PreSonus's own ATOM SQ.surface.xml into docs/CONTROL_MAP.md.

The surface XML is the authoritative control map: every physical control on the
ATOM SQ appears as a <Control> with either a raw <MidiMessage status/address> or
a <Handler class/address> that a JS handler resolves into MIDI.  We parse it
verbatim rather than transcribing by hand so the doc can never drift from the
vendor source in vendor/presonus-js/.
"""

import re
import sys
import xml.etree.ElementTree as ET
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SURFACE = ROOT / "vendor" / "presonus-js" / "ATOM SQ" / "ATOM SQ.surface.xml"
OUT = ROOT / "docs" / "CONTROL_MAP.md"

# MIDI status nibbles, for turning "#B0" into something a human can read.
STATUS_NAMES = {
    0x80: "Note Off",
    0x90: "Note On",
    0xA0: "Poly Aftertouch",
    0xB0: "CC",
    0xC0: "Program Change",
    0xD0: "Channel Aftertouch",
    0xE0: "Pitch Bend",
}


def parse_hash_int(value):
    """'#B0' -> 0xB0, '17' -> 17, None -> None."""
    if value is None:
        return None
    value = value.strip()
    if value.startswith("#"):
        return int(value[1:], 16)
    try:
        return int(value, 10)
    except ValueError:
        return None


def describe_status(status):
    if status is None:
        return ""
    kind = STATUS_NAMES.get(status & 0xF0, "?")
    channel = (status & 0x0F) + 1
    return f"{kind} ch{channel}"


def group_of(name):
    """Bucket controls by their name stem so the table reads like the panel.

    Names are one- or two-dimensional (`knob[3]`, `pad[1][0]`), so strip every
    trailing index, not just the last one.
    """
    stem = re.sub(r"(\[\d+\])+$", "", name)
    stem = re.sub(r"(LEDColor|LEDState|LEDAnimation|LED|Color)$", "", stem)
    return stem or name


def collect(surface_path):
    tree = ET.parse(surface_path)
    root = tree.getroot()

    controls = []
    # Controls can be nested inside <Controls> and any grouping elements, so walk
    # the whole tree rather than assuming a fixed depth.
    for el in root.iter("Control"):
        name = el.get("name")
        if not name:
            continue
        entry = OrderedDict(
            name=name,
            title=el.get("title", ""),
            type=el.get("type", ""),
            options=el.get("options", ""),
            status=None,
            status_raw="",
            midi_options="",
            address=None,
            handler="",
        )
        midi = el.find("MidiMessage")
        if midi is not None:
            entry["status_raw"] = (midi.get("status") or "").strip()
            entry["status"] = parse_hash_int(midi.get("status"))
            entry["address"] = parse_hash_int(midi.get("address"))
            entry["midi_options"] = (midi.get("options") or "").strip()
        handler = el.find("Handler")
        if handler is not None:
            entry["handler"] = handler.get("class", "")
            if entry["address"] is None:
                entry["address"] = parse_hash_int(handler.get("address"))
        controls.append(entry)

    return root, controls


def render(root, controls):
    lines = []
    lines.append("# ATOM SQ — Complete Control Map")
    lines.append("")
    lines.append(
        "Generated by `probe/parse_surface.py` from PreSonus's own "
        "`ATOM SQ.surface.xml` (vendored under `vendor/presonus-js/`). "
        "Do not hand-edit — regenerate."
    )
    lines.append("")
    lines.append(f"**{len(controls)} control definitions.**")
    lines.append("")
    lines.append(
        "`options=receive` means the device sends it to us; `transmit` means we "
        "send it to the device (LEDs, screen). Addresses are the MIDI note or CC "
        "number. RGB controls carry no raw MIDI — a JS handler splits the colour "
        "across channels 2/3/4."
    )
    lines.append("")

    # Ordered grouping, preserving the order PreSonus laid the panel out in.
    groups = OrderedDict()
    for c in controls:
        groups.setdefault(group_of(c["name"]), []).append(c)

    for group, items in groups.items():
        lines.append(f"## {group}")
        lines.append("")
        lines.append("| control | title | type | dir | status | addr | encoding / handler |")
        lines.append("|---|---|---|---|---|---|---|")
        for c in items:
            if c["status"] is not None:
                status = f"{describe_status(c['status'])} `0x{c['status']:02X}`"
            elif c["status_raw"]:
                # Symbolic statuses like NoteTrigger are resolved by Studio One,
                # not written as a literal byte.
                status = f"`{c['status_raw']}`"
            else:
                status = ""
            addr = f"`0x{c['address']:02X}` ({c['address']})" if c["address"] is not None else ""
            direction = c["options"].replace("fastupdate", "").strip() or ""
            extra = " ".join(x for x in (c["midi_options"], c["handler"]) if x)
            lines.append(
                "| `{name}` | {title} | {type} | {dir} | {st} | {addr} | {h} |".format(
                    name=c["name"],
                    title=c["title"],
                    type=c["type"],
                    dir=direction,
                    st=status,
                    addr=addr,
                    h=f"`{extra}`" if extra else "",
                )
            )
        lines.append("")

    # Anything in the file that is not a <Control> is worth knowing about too.
    others = OrderedDict()
    for el in root.iter():
        if el.tag not in ("Control", "MidiMessage", "Handler"):
            others[el.tag] = others.get(el.tag, 0) + 1
    lines.append("## Other elements in the surface file")
    lines.append("")
    lines.append("| element | count |")
    lines.append("|---|---|")
    for tag, count in others.items():
        lines.append(f"| `{tag}` | {count} |")
    lines.append("")

    return "\n".join(lines) + "\n"


def main():
    if not SURFACE.exists():
        sys.exit(f"surface xml not found: {SURFACE}")
    root, controls = collect(SURFACE)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(render(root, controls), encoding="utf-8")

    # Console summary — the numbers we care about while reverse engineering.
    receive = [c for c in controls if "receive" in c["options"]]
    transmit = [c for c in controls if "transmit" in c["options"]]
    addressed = [c for c in controls if c["status"] is not None]
    symbolic = sorted({c["status_raw"] for c in controls
                       if c["status"] is None and c["status_raw"]})
    print(f"controls        : {len(controls)}")
    print(f"  receive (in)  : {len(receive)}")
    print(f"  transmit (out): {len(transmit)}")
    print(f"  with raw midi : {len(addressed)}")
    statuses = sorted({c["status"] for c in addressed})
    print("statuses used   : " + ", ".join(
        f"0x{s:02X} ({describe_status(s)})" for s in statuses))
    if symbolic:
        print("symbolic status : " + ", ".join(symbolic))
    encodings = sorted({c["midi_options"] for c in controls if c["midi_options"]})
    print("midi options    : " + ", ".join(encodings))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
